/**
 * Spec-Architect Integration - Shape Phase
 *
 * Phase 1: Gather requirements, analyze assets, search for patterns.
 * Creates planning/requirements.md
 */

import * as fs from "fs/promises";
import * as path from "path";
import { contextDetector } from "../context-detector.js";

export interface ShapePhaseInput {
  featureName: string;
  description: string;
  context?: string;
}

export interface ShapePhaseOutput {
  requirementsPath: string;
  featureName: string;
  completed: boolean;
}

export class ShapePhase {
  private memoryBankPath: string;

  constructor(memoryBankPath: string) {
    this.memoryBankPath = memoryBankPath;
  }

  /**
   * Execute Shape phase: Gather requirements
   */
  async execute(input: ShapePhaseInput): Promise<ShapePhaseOutput> {
    const { featureName, description, context } = input;

    // Create specs directory for feature
    const specDir = path.join(this.memoryBankPath, "specs", this.sanitizeFeatureName(featureName));
    const planningDir = path.join(specDir, "planning");

    await fs.mkdir(planningDir, { recursive: true });

    // Generate requirements.md
    const requirements = this.generateRequirements(featureName, description, context);
    const requirementsPath = path.join(planningDir, "requirements.md");

    await fs.writeFile(requirementsPath, requirements, "utf-8");

    return {
      requirementsPath,
      featureName,
      completed: true,
    };
  }

  /**
   * Generate requirements document
   */
  private generateRequirements(featureName: string, description: string, context?: string): string {
    const now = new Date().toISOString();

    return `# ${featureName} - Requirements

> **Generated**: ${now}  
> **Phase**: Shape (Requirements Gathering)

## User Stories

### US-1: Primary User Need

As a **user**, I need **${description}**, so that **I can [benefit]**.

**Acceptance Criteria**:
- [ ] 
- [ ] 
- [ ] 

## Context

${context || "<!-- Additional context about this feature -->"}

## Assets to Leverage

<!-- List existing code, patterns, or documentation to reference -->
- 
- 
- 

## Related Patterns

<!-- Search memory_bank for similar features -->
- 
- 

## Out of Scope

<!-- Explicitly what's NOT included -->
- 
- 

## Questions

<!-- Open questions requiring answers -->
1. 

---

*This document was auto-generated by Clawtopus Spec-Architect*  
*Next: Write phase → Creates spec.md*
`;
  }

  /**
   * Sanitize feature name for directory
   */
  private sanitizeFeatureName(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  }

  /**
   * Factory: Create ShapePhase for current context
   */
  static async create(cwd: string = process.cwd()): Promise<ShapePhase> {
    const detection = await contextDetector.detectContext(cwd);
    const memoryPath = detection.internalPath || detection.externalPath;

    if (!memoryPath) {
      throw new Error("No memory bank found. Initialize memory first.");
    }

    return new ShapePhase(memoryPath);
  }
}

// Export factory
export async function shapePhase(
  input: ShapePhaseInput,
  cwd: string = process.cwd(),
): Promise<ShapePhaseOutput> {
  const phase = await ShapePhase.create(cwd);
  return phase.execute(input);
}
