import fs from "node:fs/promises";
import path from "node:path";
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  initializeMemoryBank,
  updateProjectState,
  updateDecisions,
  updateSkills,
  updateCurriculum,
  updateMemoryBank,
} from "./memory-bank-updater.js";

describe("memory-bank-updater", () => {
  const testWorkspaceDir = path.join(process.cwd(), "tmp_rovodev_test_memory_bank_unit");

  beforeEach(async () => {
    await fs.mkdir(testWorkspaceDir, { recursive: true });
  });

  afterEach(async () => {
    await fs.rm(testWorkspaceDir, { recursive: true, force: true });
  });

  describe("initializeMemoryBank", () => {
    it("returns true when memory_bank/ does not exist and creates it", async () => {
      const result = await initializeMemoryBank(testWorkspaceDir);
      expect(result).toBe(true);

      const memoryBankDir = path.join(testWorkspaceDir, "memory_bank");
      const stats = await fs.stat(memoryBankDir);
      expect(stats.isDirectory()).toBe(true);
    });

    it("returns false when memory_bank/ already exists", async () => {
      const memoryBankDir = path.join(testWorkspaceDir, "memory_bank");
      await fs.mkdir(memoryBankDir, { recursive: true });

      const result = await initializeMemoryBank(testWorkspaceDir);
      expect(result).toBe(false);
    });

    it("creates PROJECT_CONTEXT.md", async () => {
      await initializeMemoryBank(testWorkspaceDir);

      const contextPath = path.join(testWorkspaceDir, "memory_bank", "PROJECT_CONTEXT.md");
      const content = await fs.readFile(contextPath, "utf-8");

      expect(content).toContain("# Project Context");
      expect(content).toContain("Auto-generated by Clawtopus");
    });
  });

  describe("updateProjectState", () => {
    it("creates PROJECT_STATE.md if it doesn't exist", async () => {
      await initializeMemoryBank(testWorkspaceDir);
      await updateProjectState(testWorkspaceDir, "Implemented new feature X");

      const statePath = path.join(testWorkspaceDir, "memory_bank", "PROJECT_STATE.md");
      const content = await fs.readFile(statePath, "utf-8");

      expect(content).toContain("# Project State");
      expect(content).toContain("Implemented new feature X");
    });

    it("prepends new entries (newest first)", async () => {
      await initializeMemoryBank(testWorkspaceDir);
      await updateProjectState(testWorkspaceDir, "First entry");
      await updateProjectState(testWorkspaceDir, "Second entry");

      const statePath = path.join(testWorkspaceDir, "memory_bank", "PROJECT_STATE.md");
      const content = await fs.readFile(statePath, "utf-8");

      const firstIndex = content.indexOf("First entry");
      const secondIndex = content.indexOf("Second entry");
      expect(secondIndex).toBeLessThan(firstIndex);
    });
  });

  describe("updateDecisions", () => {
    it("creates DECISIONS.md with entries", async () => {
      await initializeMemoryBank(testWorkspaceDir);
      await updateDecisions(testWorkspaceDir, ["Use TypeScript", "Adopt React hooks"]);

      const decisionsPath = path.join(testWorkspaceDir, "memory_bank", "DECISIONS.md");
      const content = await fs.readFile(decisionsPath, "utf-8");

      expect(content).toContain("# Architectural Decisions");
      expect(content).toContain("Use TypeScript");
      expect(content).toContain("Adopt React hooks");
    });

    it("skips update when decisions array is empty", async () => {
      await initializeMemoryBank(testWorkspaceDir);
      await updateDecisions(testWorkspaceDir, []);

      const decisionsPath = path.join(testWorkspaceDir, "memory_bank", "DECISIONS.md");
      const exists = await fs
        .access(decisionsPath)
        .then(() => true)
        .catch(() => false);
      expect(exists).toBe(false);
    });
  });

  describe("updateSkills", () => {
    it("creates SKILLS.md with entries", async () => {
      await initializeMemoryBank(testWorkspaceDir);
      await updateSkills(testWorkspaceDir, ["Custom hook pattern", "Error boundary setup"]);

      const skillsPath = path.join(testWorkspaceDir, "memory_bank", "SKILLS.md");
      const content = await fs.readFile(skillsPath, "utf-8");

      expect(content).toContain("# Project Skills");
      expect(content).toContain("Custom hook pattern");
    });
  });

  describe("updateCurriculum", () => {
    it("creates CURRICULUM.md with entries", async () => {
      await initializeMemoryBank(testWorkspaceDir);
      await updateCurriculum(testWorkspaceDir, ["Learned React Context API", "Mastered Vitest"]);

      const curriculumPath = path.join(testWorkspaceDir, "memory_bank", "CURRICULUM.md");
      const content = await fs.readFile(curriculumPath, "utf-8");

      expect(content).toContain("# Learning Curriculum");
      expect(content).toContain("Learned React Context API");
    });
  });

  describe("updateMemoryBank", () => {
    it("updates all memory_bank files when context is provided", async () => {
      await updateMemoryBank({
        workspaceDir: testWorkspaceDir,
        sessionSummary: "Completed authentication module",
        decisions: ["Use JWT for auth"],
        skills: ["JWT token validation pattern"],
        learnings: ["Learned about OAuth2 flows"],
      });

      const statePath = path.join(testWorkspaceDir, "memory_bank", "PROJECT_STATE.md");
      const stateContent = await fs.readFile(statePath, "utf-8");
      expect(stateContent).toContain("Completed authentication module");

      const decisionsPath = path.join(testWorkspaceDir, "memory_bank", "DECISIONS.md");
      const decisionsContent = await fs.readFile(decisionsPath, "utf-8");
      expect(decisionsContent).toContain("Use JWT for auth");

      const skillsPath = path.join(testWorkspaceDir, "memory_bank", "SKILLS.md");
      const skillsContent = await fs.readFile(skillsPath, "utf-8");
      expect(skillsContent).toContain("JWT token validation pattern");

      const curriculumPath = path.join(testWorkspaceDir, "memory_bank", "CURRICULUM.md");
      const curriculumContent = await fs.readFile(curriculumPath, "utf-8");
      expect(curriculumContent).toContain("Learned about OAuth2 flows");
    });

    it("auto-initializes memory_bank if it doesn't exist", async () => {
      await updateMemoryBank({
        workspaceDir: testWorkspaceDir,
        sessionSummary: "Initial setup",
      });

      const memoryBankDir = path.join(testWorkspaceDir, "memory_bank");
      const stats = await fs.stat(memoryBankDir);
      expect(stats.isDirectory()).toBe(true);
    });
  });
});
